# Generated by Django 4.2 on 2023-04-20 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(through='follows.UserFollows', to=settings.AUTH_USER_MODEL, verbose_name='suit'),
        ),
    ]
