# Generated by Django 4.2 on 2023-04-25 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0001_initial'),
        ('authentication', '0002_user_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(related_name='followers', through='follows.UserFollows', to=settings.AUTH_USER_MODEL, verbose_name='suit'),
        ),
    ]
